  function FACTORY() 
  {
    this.id = 0;
    this.func = (function () 
    {
      return 5;
    });
    this.id = this.func();
  }
  try
{    var obj = new FACTORY();}
  catch (e)
{    $ERROR('#1: var obj = new FACTORY() does not lead to throwing exception. Actual: Exception is ' + e);}

  {
    var __result1 = obj.id !== 5;
    var __expect1 = false;
  }
  