  try
{    {
      var __result1 = Function.prototype() !== undefined;
      var __expect1 = false;
    }}
  catch (e)
{    $ERROR('#1.1: The Function prototype object is itself a Function object that, when invoked, accepts any arguments and returns undefined: ' + e);}

  