  try
{    Function.call(this, "var #x  = 1;");}
  catch (e)
{    {
      var __result1 = ! (e instanceof SyntaxError);
      var __expect1 = false;
    }}

  